# Generated by Django 5.0.6 on 2024-11-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_recipe_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
